---
title: " "
pagetitle: "Burak Sonmez"
---

<link rel="stylesheet" href="styles.css" type="text/css">


### **Postgraduate courses**

Fall 2020: Quantitative Social Research Methods, London School of Economics & Political Science, *Lectures*.

Spring 2019: Introduction to Quantitative Analysis, London School of Economics & Political Science, *Seminars*.

Fall 2018: Introduction to Quantitative Analysis for Media & Communications, London School of Economics & Political Science, *Seminars*.

Summer 2018: Longitudinal Data Anaylsis, Essex Summer School in Social Science Data Analysis, *Lab sessions*.


### **Undergraduate courses**

Spring 2021: Researching London: Advanced Social Research Methods, London School of Economics & Political Science, *Lectures & Lab sessions*.

Fall 2020: Data in Society, London School of Economics & Political Science, *Lectures & Seminars*.

Spring 2020: Models and Measurement in Quantitative Sociology, University of Essex, *Lectures*.

Fall 2019: Researching Social Life II, University of Essex, *Seminars*.

Spring 2019: Ethics and Public Policy, University of Essex, *Seminars*.

Fall 2016-Spring 2018: Researching Social Life I, University of Essex, *Seminars*.

Spring 2011-2012: Economic Theory for Engineers, Bilkent University, *Teaching assistant*.

Fall 2010-2011: Mathematics for Economists, Bilkent University, *Teaching assistant*.

### **Short courses**

Jun 2021: Quantitative Methods of Empirical Social Research, Pompeu Fabra University (UPF), The RECSM Summer
Methods School,*Lectures*.

Feb 2019: Online Data Collection through Crowdsourcing Marketplaces, University of Essex, *Lectures*.

Jun 2018: Online Data Collection through Crowdsourcing Marketplaces, European University Institute, *Lectures*. 

### **Workshops**

Jun 2021: LSE Workshop on Experimental Sociology. Please find the Call for Submissions [here](files/LSE_WES.pdf).

